### ISSUE TITLE
Failed to publish the Contoso.Apps.SportsLeague.Admin

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Modern-cloud-apps#53] opened 2020-02-03 14:34 UTC
Exercise 1:- Task 3:- subtask 3 :- while publishing the Contoso.Apps.SportsLeague.Admin web application it is showing an error ... after updating the nuget package publishing of the application  was successful but no content was there in webpage

**Comment by thiagofborn** [comment] 2020-02-03 18:26
Hi Team. 

I hope you guys are doing fine. 

It is to complete the @Gvashi narrative:

After adding the "EasyAuth" dependency, the response is an "error 401".  It seems to be a lack of authorization, caused by some incompatibility between the way the class handles the authorization. 

Once we comment the EasyAuth at line 32 File Startup.cs:

```csharp
services.AddAuthentication().AddEasyAuthAuthentication((o) => { });
```
 And line 20 on the file ../Controllers/HomeController.cs 

```csharp
[Authorize(AuthenticationSchemes = "EasyAuth")]
```

Which kills the EasyAuth... It is possible to see the site. I am not a "csharp" specialist.  
So, please, I need some help. 

Regards, 

Thiago

**Comment by Gvashi** [comment] 2020-02-04 08:00
Hi 
@timahenning  is there any update .

**Comment by Gvashi** [comment] 2020-02-04 13:33
@timahenning  any update on that , even the EasyAuth classes files are blank.

**Comment by thiagofborn** [comment] 2020-02-04 16:48
@Gvashi, you probably will run into another issue with at "Task 5: Deploying the Offers Web API". 

I have managed to "fix it":  Reference: [ Cloned: [1](https://github.com/thiagofborn/MCW-Modern-cloud-apps)]

**Comment by DawnmarieDesJardins** [comment] 2020-02-14 22:52
@timahenning @crpietschmann 
Please review & advise

**Comment by crpietschmann** [comment] 2020-02-26 22:47
I committed a fix for the "empty" EasyAuth code files (commit #86daab1). This should fix the issue. I'm leaving this Issue open for now, as I'm going to run through this one again to make sure that fixed it.

**Comment by SeeratArora** [comment] 2020-03-16 11:06
[Exercise 1: Task 3: Subtask 3:](https://github.com/microsoft/MCW-Modern-cloud-apps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Modern%20cloud%20apps.md#subtask-3-deploy-the-call-center-admin-web-app-from-visual-studio)

**Comment by timahenning** [comment] 2020-03-16 18:46
@SeeratArora Is this new comment related to the commit that Chris referenced above?

Tim

**Comment by SeeratArora** [comment] 2020-03-17 10:57
Yes @timahenning , can we get updates in this?

**Comment by crpietschmann** [comment] 2020-03-17 14:54
Sorry for the delay, I'm currently working on updating this MCW, and will get any issue here resolved soon. I'll update you here, when that is completed.

**Comment by DawnmarieDesJardins** [comment] 2020-03-17 19:12
@SeeratArora @crpietschmann 
Hi Seerat.  Are you testing this lab for upcoming presentations?

**Comment by SeeratArora** [comment] 2020-03-17 19:14
Hi Dawnmarie,

Yes I'm testing this for upcoming presentations.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aautere** [comment] 2020-03-17 19:46
I'm having the same issue as Seerat in 1.3.3. (also the commenting of line 20 helped with the exception). I would be really nice if you get this resolved. I'm having this workshop with a client this weeks Thursday.  I understand that it might come a bit too quickly, so no worries if it takes longer :)

**Comment by DawnmarieDesJardins** [comment] 2020-03-17 20:23
Hi gentlemen!  We are currently working on a quarterly update to this workshop but it won't be complete until the first part of April.  In the meantime, our author is working on a fix for this issue and will have this out as soon as possible, thank you for your patience.

**Comment by andresmmujica** [comment] 2020-03-19 00:51
We can confirm that this issue gets solved by commenting on line 20 and removing that comment just before testing authentication in the web site.

**Comment by crpietschmann** [comment] 2020-03-19 01:36
I commented out Line 20 as mentioned above and committed it to master. I'll made that change first, to help you with the issue. I will still be running through the app to make sure I can validate this.

**Comment by crpietschmann** [comment] 2020-03-19 16:52
@andresmmujica @aautere @SeeratArora I have confirmed that commenting out Line 20 in the Admin `HomeController.cs` does appear to fix the issue. Since I made that quick change yesterday already in master, you should already have the fix in place for anyone delivering this today. :)

FYI @DawnmarieDesJardins

**Comment by timahenning** [comment] 2020-04-03 13:15
Fix delivered and no further comments from the field.

**Closed by timahenning** 2020-04-03 13:15 UTC
