### ISSUE TITLE
Exercise 1, Task 1, subtask 7, Step 17: Getting error.

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Modern-cloud-apps#78] opened 2021-02-02 11:53 UTC
Exercise 1, Task 1, subtask 7, step 17: Getting error in web app.

Have followed all the steps as mentioned, yet getting this error while launching web app.

![image](https://user-images.githubusercontent.com/32365275/106596657-57999d80-657b-11eb-8e35-61c8a80a4353.png)

**Comment by saimachi** [comment] 2021-02-04 04:19
Hi @Eddevinc,

Since this error can be caused by multiple different issues, navigate to your App Service in Azure portal. Then, search for and launch the **Console**. Then, execute `Contoso.Apps.SportsLeague.Web.exe`. If you receive an error about the application not being able to access the Secrets stored in Key Vault, then navigate to your Key Vault and ensure that an access policy (`Get` and `List` secrets) exists for your App Service instance's managed identity. It will be called something like `contosoapp[SUFFIX]`. Once you update the Key Vault access policies, you will need to restart your App Service instance (this can be done from the **Overview** tab of your App Service).

If these steps don't work, post the output of executing the web application in the console.

**Comment by Eddevinc** [comment] 2021-02-05 10:37
Hi @saimachi 

I tried the above step where we execute the "Contoso.Apps.SportsLeague.Web.exe" command in console of app service, and I am getting the following error.

Plus access policy is also correctly configured.

![image](https://user-images.githubusercontent.com/32365275/107022931-f6b4d400-67cb-11eb-9718-15af0b13aef9.png)

**Comment by timahenning** [comment] 2021-02-05 15:12
Hi @Eddevinc, Thank you for the picture.  It helps.  Did you verify your Key Vault access is correct and accessible by the application?  If your app cannot access the credentials or the values are not correct, you might get a error message like the one you posted.

**Comment by timahenning** [comment] 2021-02-09 00:42
Hi @Eddevinc,

Any update?

**Comment by sumitmalik51** [comment] 2021-02-10 08:49
Hello @timahenning, I have run through the lab today and I didn't face this issue, Maybe @Eddevinc missed the key vault string values. Thanks you can close this issue.

**Closed** 2021-02-12 03:04 UTC
