### ISSUE TITLE
Web App not opening after publishing it with the correct connection strings

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Modern-cloud-apps#51] opened 2020-01-28 11:52 UTC
In Exercise 1 subtask 4, the Web App not opening after publishing it with the correct connection strings. When we try to open the web app in a browser, also tried to Restart the App Service for the app and redeploy the code. it displays as follows
![012354100](https://user-images.githubusercontent.com/53901647/73261744-b30baf80-41f2-11ea-9439-19a2cc18817e.JPG)

**Comment by thiagofborn** [comment] 2020-01-28 19:48
Hi, 

I'm having the same experience.  I need to debug further, but I guess it is related to the **EasyAuth** library:

Reference:
 <https://github.com/MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth>

**Comment by crpietschmann** [comment] 2020-01-28 22:16
Make sure there aren't any errors in the config file and the connection strings are set correctly.

I have seen this error come up some times, and to fix it I needed to Restart the App Service for the app and redeploy the code. There have been times where I had to delete the App Service Web App resource in Azure, and create a new one, deploy, and then it worked.

Here's the troubleshoot description Microsoft has in the docs for this error message:

> The worker process fails. The app doesn't start.
>
> The ASP.NET Core Module attempts to start the .NET Core CLR in-process, but it fails to start. The cause of a process startup failure can usually be determined from entries in the Application Event Log and the ASP.NET Core Module stdout log.
>
> A common failure condition is the app is misconfigured due to targeting a version of the ASP.NET Core shared framework that isn't present. Check which versions of the ASP.NET Core shared framework are installed on the target machine.

https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1

I know this error is frustrating, but it's not related to any of the lab steps. There seems to be some times this error comes up when a .NET Core app starts up in App Service. Please let us know if you have any other issues with the lab steps. Thanks!

**Comment by Gvashi** [comment] 2020-01-29 10:30
Exercise 1:task 2: subtask 5
Your solution is not working it is showing the same error
![0](https://user-images.githubusercontent.com/53901647/73349037-743c2f00-42b0-11ea-86d1-5f20bd96b9f7.JPG)

Can you please look into this.

**Comment by christiannagel** [comment] 2020-01-29 12:18
I think this is a duplicate of #46

**Comment by Gvashi** [comment] 2020-01-29 12:21
Yes,
But in different step

**Closed** 2020-01-30 13:34 UTC
