### ISSUE TITLE
Exercise 3, Task 3, Step 14: Not able to run User flow.

### ISSUE THREAD

**Issue by Eddevinc** [microsoft/MCW-Modern-cloud-apps#77] opened 2021-02-01 14:44 UTC
Exercise 3, Task 3, Step 14: Not able to run User flow.
![image](https://user-images.githubusercontent.com/32365275/106473672-0e3d4580-64ca-11eb-946e-a2c435bc7bc2.png)

**Comment by saimachi** [comment] 2021-02-05 04:35
Hi @Eddevinc,

I was not able to reproduce the same error. I notice that your **Application** and **Reply URL** fields are empty. Perhaps you should try recreating the **Contoso B2C Application** application registration, which is done in Exercise 3, Task 2.

Moreover, according to [this GitHub issue,](https://github.com/MicrosoftDocs/azure-docs/issues/55822) you need to ensure that when you set the **Redirect URI** for the application registration, the URI needs to be set for **Web**, not any of the other options.

**Comment by sumitmalik51** [comment] 2021-02-10 08:10
Hello @saimachi, I have tried again and facing the same issue while running the userflow, The thing is I am not able to select the application in User flow blade. 
![image](https://user-images.githubusercontent.com/45102602/107481911-f38f5e80-6ba4-11eb-8377-36d90c89e673.png)
![image](https://user-images.githubusercontent.com/45102602/107481927-f8541280-6ba4-11eb-85ff-22db8743e4f8.png)
I have tried recreating the application but still its not working.
![image](https://user-images.githubusercontent.com/45102602/107482330-8b8d4800-6ba5-11eb-9779-a258ea8dc62a.png)


Also I have an active environment and we can check on this issue over call or I can send you the environment details, so that we can check what is the exact issue here. 
Thanks

**Comment by saimachi** [comment] 2021-02-17 00:14
Hi @sumitmalik51,

As [this](https://stackoverflow.com/questions/64739401/ad-b2c-test-user-flow-does-not-allow-selection-of-application-registration) issue indicates, you will need to ensure that any identity provider can be used for this user flow. 

Another possibility you could try would be switching your tenant to your B2C directory in Azure portal, and then try running the user flow in that directory. The image below demonstrates how to do that.

![2021-02-16_16-05-02](https://user-images.githubusercontent.com/37318129/108137612-0f957300-7071-11eb-8847-180cfca36b1c.png)

Lastly, Microsoft provides an _https://jwt.ms_ site to test sample user flows. If none of the steps above succeed, could you try creating a sample application with the mentioned URL as the Reply URL? [Here's](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga) the process for creating an app registration. In my case, this works without a problem. Let me know what you see when you try this approach.

![2021-02-16_16-11-23](https://user-images.githubusercontent.com/37318129/108137881-a5c99900-7071-11eb-8345-7840befeb5e8.png)

**Comment by saimachi** [comment] 2021-02-23 06:26
Hi @sumitmalik51,

Did my suggested fixes work for you? Let us know the status of your environment, or we may close this issue.

**Comment by sumitmalik51** [comment] 2021-02-23 16:55
Hello @saimachi,
We'll run through the lab tomorrow and will give you an update on the above issue.
Thanks for following up.

**Comment by sumitmalik51** [comment] 2021-02-24 23:03
Hello @saimachin, I was able to run through this step. Thanks you can close the issue.

**Closed** 2021-02-24 23:10 UTC
